### ISSUE TITLE
rotLove causes an error when loaded

### ISSUE THREAD

**Issue by Nuthen** [paulofmandown/rotLove#21]
The updated 30log code has a return statement at the end of it, which doesn't allow the rest of the library to be loaded.

**Comment by paulofmandown** [comment]
Yep, I broke it...

In fixing that return, I've found that there are a bunch more fundamental changes to 30log that I'm going to need to address also. So, it's going to be broken for a minute. Hopefully only for a day or two. I'll probably make a new release off of the pre-"Updating 30log" version, so that there's a good up to date copy for people to easily grab and use.

**Comment by paulofmandown** [comment]
Addressed in [c92de2](https://github.com/paulofmandown/rotLove/commit/c92de2979c4687d0974029af751ae7a80b7fc791)
