### ISSUE TITLE
Hangs with a white screen with Love 11.1

### ISSUE THREAD

**Issue by armyofevilrobots** [paulofmandown/rotLove#58]
Any example, or any new project hangs with a blank white screen at startup. Game is running, and clover-Q quits just fine, but the screen never updates.

10.x and earlier don't seem to have this problem.

Discovered on Mac OSX Sierra with Love 11.1.

**Comment by paulofmandown** [comment]
I have good news and bad news. The good is that these projects aren't hanging and everything is working as written. The bad is that everything is being drawn white because of the changes to how love expects you to define colors. Previously colors were a table of integers ranged 0-255. That table now expects floats ranged 0-1. Since the vast majority of colors in `color.lua` are greater than one, everything is white.

Shouldn't be a problem, but I'm going to break compatibility with older versions to support the new color format

Fix should be in soon

**Comment by paulofmandown** [comment]
Quick and dirty fix is on the develop branch now
